### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by amoedoamorim** [leejaen/React-Desktop-Notification#2]
Hello Leejaen,

Thanks for the nice Notification component.
When are you planning to update the npm package with the latest changes? (name parameter)

Thanks,

Alex

**Comment by leejaen** [comment]
Hi amoedoamorim, 

Thanks for your pr, your idea & code are awesome! I have released a new version 1.0.5 of package on npm, please check it or update.

👍 👍 👍
