### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by gate3** [leejaen/React-Desktop-Notification#4]
Nice library, simple and straight to the point. I love it. The issue i am having is that when i click on the notification it doesn't redirect me to the page i specified when creating the notification, it just takes me to the currently open browser window.

**Comment by leejaen** [comment]
Sorry about this problem, could you give me your specified URL and browser window screenshot? or simple code? let me try to fix it if it is a bug.

**Comment by gate3** [comment]
`_showDesktopNotification ({title, message, page}) {
    Notifier.start(title, message, page, '../assets/img/favicons/apple-icon-76x76.png', this.constant.website)
  }`

This is the snippet that displays it. Everything is being passed in properly and it displays as it should, but on clicking on the notification. It just redirects to an open page.

![image](https://user-images.githubusercontent.com/3597437/28196124-6deb9bb4-6846-11e7-9570-9bceba18d694.png)

**Comment by leejaen** [comment]
_showDesktopNotification ({title, message, page}) { 
`console.log("Notification values are: ",title, message, page, this.constant.website);`
Notifier.start(title, message, page, '../assets/img/favicons/apple-icon-76x76.png', this.constant.website) }

Could you show me values in the above console.log?

**Comment by gate3** [comment]
Can you just replace them with anything for now, so we can test and make
sure it works

**Comment by leejaen** [comment]
@gate3 Hi Doyin Olarewaju, I got this bug and have been fixed it, please check the last version 1.0.7 to make sure if it works well?

@SirSaunders Hi Johnathan, for your project,  if you want to focus the main window, please use the new function `Notifier.focus("Title","Here is context","www.google.com","validated image url");`  instead of `Notifier.start()`.
