### ISSUE TITLE
existence check fails in IE 11

### ISSUE THREAD

**Issue by Waize** [leejaen/React-Desktop-Notification#7]
Hey, 

first of all nice component! 
Since we need to support IE11, I tested your component there. Problem ist, that your check, if the browser supports Notification fails in IE11. (https://github.com/leejaen/React-Desktop-Notification/blob/master/index.js#L16)

A working way is 
`
if ('Notification' in window) {
// API is supported
}
`

Sadly I have to wrap your Component-Call in this if-case. 
Could you please use the check I provide?

**Comment by Waize** [comment]
@leejaen thx for accepting the PR. will there be the new version soon? :)

**Comment by leejaen** [comment]
@Waize Sure, the last version 1.0.9 already on npm: https://www.npmjs.com/package/react-desktop-notification .
